name: Publicar en GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache de dependencias
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ hashFiles('requirements.txt') }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Compilar y publicar
        run: mkdocs gh-deploy --force
